/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Link from "next/link";
import { Reveal } from "@/ui/components";
import { Footer, Header } from "@/ui/sections";

const SITE_URL = "https://www.sentium.app";
const LAST_UPDATED = "18 June 2026";
const SUPPORT_EMAIL = "support@sentium.app";

export const metadata: Metadata = {
  title: "Vello — Terms of use",
  description: "The terms governing your use of the Vello holistic health app by Sentium Ltd.",
  alternates: { canonical: `${SITE_URL}/vello/terms/` },
};

export default function VelloTerms() {
  return (
    <>
      <Header />
      <main className="pt-32 pb-20 sm:pt-40 sm:pb-28 grain relative overflow-hidden">
        <div className="container-prose relative">
          <Reveal>
            <nav className="flex items-center gap-2 text-sm mb-10" aria-label="Breadcrumb" style={{ color: "var(--color-muted)" }}>
              <Link href="/" className="hover:underline underline-offset-4">Home</Link>
              <span aria-hidden="true">/</span>
              <Link href="/vello/" className="hover:underline underline-offset-4">Vello</Link>
              <span aria-hidden="true">/</span>
              <span style={{ color: "var(--color-fg)" }}>Terms</span>
            </nav>
          </Reveal>

          <Reveal>
            <h1 className="font-display text-4xl sm:text-5xl tracking-tight leading-[1.05]">Vello — Terms of use</h1>
            <p className="mt-4 text-sm" style={{ color: "var(--color-muted)" }}>Last updated: {LAST_UPDATED}</p>
          </Reveal>

          <article className="legal mt-10 space-y-8">
            <Reveal>
              <section>
                <h2>1. Agreement</h2>
                <p>
                  By creating an account or using the Vello mobile app ("Vello") you agree to these Terms. If you don't
                  agree, don't use Vello. Vello is operated by <strong>Sentium Ltd</strong> (company number 16512683),
                  registered in England and Wales.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>2. What Vello is — and is not</h2>
                <p>
                  Vello is a <strong>wellness and education tool</strong>. It helps you log, organise, and reflect on
                  your own health data, and offers AI-generated discussion prompts you can take to your clinician.
                </p>
                <p>
                  <strong>Vello is not a medical device.</strong> It does not diagnose, treat, cure, or prevent any
                  disease. It is not a replacement for professional medical advice, diagnosis, or treatment. Never delay
                  seeking medical advice because of something Vello has shown you.
                </p>
                <p>
                  If you may be experiencing a medical emergency, <strong>call your local emergency services
                  immediately</strong> (999 in the UK, 911 in the US, 112 in the EU).
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>3. Eligibility</h2>
                <p>
                  Vello is intended for adults (18+) who can give informed consent to processing their own health data.
                  You must provide a real email address and accurate information when relevant for Vello to be useful.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>4. Your account</h2>
                <p>
                  You are responsible for keeping your sign-in method secure — your Apple ID, Google account, or
                  email/password as appropriate. Notify us immediately if you suspect unauthorised access.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>5. Acceptable use</h2>
                <p>Don't use Vello to:</p>
                <ul>
                  <li>Upload data belonging to anyone other than yourself.</li>
                  <li>Reverse-engineer, scrape, or attempt to extract our underlying AI models.</li>
                  <li>Send abusive, illegal, or rights-infringing content via the Care AI.</li>
                  <li>Bypass authentication, rate limits, or other technical protections.</li>
                </ul>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>6. AI-generated content</h2>
                <p>
                  Care AI responses are generated by large language models (OpenAI GPT-4 family, accessed via Azure
                  OpenAI in the UK) given the context you provide. These models can produce <strong>plausible-sounding
                  but incorrect statements</strong>. Treat every response as a starting point for conversation with a
                  qualified clinician — never as a definitive assessment.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>7. Data and privacy</h2>
                <p>
                  Use of Vello is governed by our <Link href="/vello/privacy/" className="underline">Privacy Policy</Link>.
                  In short: your data lives in Azure UK South, is encrypted at rest and in transit, is never sold, and
                  can be deleted by you at any time from Settings.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>8. Subscriptions and pricing</h2>
                <p>
                  Vello is currently free during early access. If we introduce paid features in future, you will be
                  notified in-app and never charged without explicit consent.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>9. Disclaimers and limits of liability</h2>
                <p>
                  Vello is provided "as is". To the maximum extent permitted by law, Sentium Ltd disclaims all
                  warranties, express or implied. We are not liable for any health outcomes, decisions, or harms
                  resulting from acting on (or failing to act on) information surfaced by Vello.
                </p>
                <p>
                  Nothing in these terms limits our liability for death or personal injury caused by negligence, fraud,
                  or any other liability that cannot be excluded under English law.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>10. Termination</h2>
                <p>
                  You can end the agreement any time by deleting your account in Settings. We may suspend or terminate
                  access for serious or repeated breaches of these Terms (notice given where reasonable).
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>11. Intellectual property</h2>
                <p>
                  The Vello app, web product, and all associated materials — including the Vello name, logo, visual
                  design, source code, written content, and the Care AI prompts and pillar logic — are owned by
                  Sentium Ltd and protected by copyright, trade mark, and other intellectual-property laws. You receive
                  a personal, non-transferable, revocable licence to use Vello for your own wellness and education,
                  subject to these Terms. Nothing in these Terms transfers ownership of any of our intellectual
                  property to you.
                </p>
                <p>
                  Conversely, the data <em>you</em> enter into Vello — your bio, baselines, logs, lab values, and
                  Care AI prompts — remains <strong>yours</strong>. You grant Sentium Ltd a limited licence to process
                  that data solely to provide the service to you, as described in the{" "}
                  <Link href="/vello/privacy/" className="underline">Privacy Policy</Link>.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>12. Governing law</h2>
                <p>
                  These Terms are governed by the laws of England and Wales. Disputes are subject to the exclusive
                  jurisdiction of the English courts.
                </p>
              </section>
            </Reveal>

            <Reveal>
              <section>
                <h2>13. Contact</h2>
                <p>
                  <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>
                  <br />
                  Sentium Ltd · London E17 3NU · United Kingdom · Company no. 16512683
                </p>
              </section>
            </Reveal>
          </article>
        </div>
      </main>
      <Footer />
    </>
  );
}
